# Generated by Django 4.2.23 on 2025-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_comment='手机号码', max_length=20, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
