# Generated by Django 4.2.23 on 2025-08-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(db_comment='id', primary_key=True, serialize=False)),
                ('project_code', models.CharField(db_comment='项目编码', max_length=32, unique=True)),
                ('project_name', models.CharField(db_comment='项目名称', max_length=128, unique=True)),
                ('description', models.TextField(db_comment='项目描述', null=True)),
                ('project_type', models.CharField(db_comment='项目类型', max_length=128)),
                ('project_status', models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '完成'), (3, '暂停'), (4, '终止')], db_comment='项目状态', default=0)),
                ('start_date', models.DateField(db_comment='项目开始日期', null=True)),
                ('end_date', models.DateField(db_comment='项目结束时间', null=True)),
                ('created_at', models.DateField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateField(auto_now=True, db_comment='更新时间')),
            ],
        ),
    ]
