# Generated by Django 4.2.27 on 2026-01-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(db_comment='id', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_comment='项目名称', max_length=128, unique=True)),
                ('description', models.TextField(db_comment='项目描述', null=True)),
                ('project_type', models.CharField(db_comment='项目类型', max_length=64, null=True)),
                ('project_status', models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '完成'), (3, '暂停'), (4, '终止')], db_comment='项目状态', default=0)),
                ('start_date', models.DateField(db_comment='计划开始日期', null=True)),
                ('end_date', models.DateField(db_comment='计划结束日期', null=True)),
                ('created_user_id', models.IntegerField(db_comment='创建人id')),
                ('created_user', models.CharField(db_comment='创建人', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('deleted_at', models.DateTimeField(db_comment='删除时间', null=True)),
            ],
        ),
    ]
