# Generated by Django 4.2.27 on 2026-01-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['-created_at'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelTable(
            name='projectmodel',
            table='project',
        ),
    ]
