# Generated by Django 4.2.27 on 2026-02-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalTestCaseModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(db_column='所属项目id')),
                ('case_title', models.CharField(db_comment='用例标题', max_length=255)),
                ('precondition', models.TextField(blank=True, db_comment='前置条件', null=True)),
                ('test_steps', models.TextField(db_comment='测试步骤')),
                ('expected_result', models.TextField(db_comment='预期结果')),
                ('module', models.CharField(db_comment='所属模块', max_length=100, null=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'P0-最高'), (1, 'P1-高'), (2, 'P2-中'), (3, 'P3-低')], db_comment='优先级，P0-最高，P1-高，P2-中，P3-低', default=0)),
                ('comment', models.TextField(blank=True, db_comment='备注', null=True)),
                ('case_source', models.SmallIntegerField(choices=[(0, '手动创建'), (1, 'AI生成'), (2, '导入')], db_comment='用例来源，0-手动，1-AI生成，2-导入', default=0)),
                ('requirement_id', models.IntegerField(db_comment='所属需求id')),
                ('execution_status', models.SmallIntegerField(choices=[(0, '未执行'), (1, '执行中'), (2, '通过'), (3, '失败')], db_comment='最后执行状态, 0-未执行，1-执行中，2-通过，3-失败', default=0)),
                ('created_user_id', models.IntegerField(db_comment='创建人id', null=True)),
                ('created_user', models.CharField(db_comment='创建人', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='删除时间', null=True)),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'functional_test_case',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
