# Generated by Django 4.2.27 on 2026-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functional_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionaltestcasemodel',
            name='requirement_document_id',
            field=models.IntegerField(db_comment='所属需求文档id', default=1),
            preserve_default=False,
        ),
    ]
