"""
Django settings for back project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

from config.env_config import ENV_FILE_PATH

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^zm%muipw_(-@w^cy2kd7d8)k4l)y4jv#*+1ffw4d9!agx!^qn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'webtest.yeejay.com',
    'backend',  # Docker 容器内部访问
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # Celery 相关应用
    'django_celery_results',
    'django_celery_beat',
    # 自定义应用
    'users',
    'api_auto_test',
    'projects',
    'requirements',
    'functional_test'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
load_dotenv(ENV_FILE_PATH)
DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 需要设置 AUTH_USER_MODEL 字段才能将用户模型转移到自定义模型中
# 否则会即使 user 模型中继承了 AbstractUser 类也会因为都使用了权限模型导致无法迁移
AUTH_USER_MODEL = 'users.User'

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # 你的前端地址
]

#  SMTP 服务器配置，用于发送邮件
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_HOST_USER = '927009187@qq.com'
EMAIL_HOST_PASSWORD = 'ojewodtmabwobbaj'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ==================== Celery 配置 ====================
# 消息代理配置 - 使用 RabbitMQ
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://webtest:webtest@localhost:5672//')

# Windows 开发环境使用 solo 进程池（避免 prefork 权限问题）
# 生产环境（Linux）可移除此配置
import platform
if platform.system() == 'Windows':
    CELERY_WORKER_POOL = 'solo'

# 任务结果存储（使用 Django 数据库）
CELERY_RESULT_BACKEND = 'django-db'

# 序列化配置
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 时区配置
CELERY_TIMEZONE = 'Asia/Shanghai'

# 任务追踪
CELERY_TASK_TRACK_STARTED = True

# 任务超时时间（1 小时）
CELERY_TASK_TIME_LIMIT = 3600

# ==================== Celery Beat 定时任务配置 ====================
CELERY_BEAT_SCHEDULE = {
    # 每分钟检查接口测试定时任务
    'check-api-test-scheduled-tasks': {
        'task': 'tasks.schedule_tasks.ScheduleTaskService.checkScheduledTasks',
        'schedule': 60.0,  # 每 60 秒执行一次
    },
    # 每 5 分钟更新定时任务执行状态
    'update-schedule-execution-status': {
        'task': 'tasks.schedule_tasks.ScheduleTaskService.updateExecutionStatus',
        'schedule': 300.0,  # 每 300 秒执行一次
    },
}