# Generated by Django 4.2.27 on 2025-12-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDocuments',
            fields=[
                ('id', models.AutoField(db_comment='id', primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(db_comment='所属项目id')),
                ('doc_name', models.CharField(db_comment='文档名称', max_length=255)),
                ('version', models.CharField(db_comment='版本号，格式如 1.0.0', max_length=50)),
                ('cos_access_url', models.URLField(db_comment='cos访问url', null=True)),
                ('file_size', models.BigIntegerField(db_comment='文件大小（字节）')),
                ('comment', models.TextField(db_comment='备注说明', null=True)),
                ('created_user', models.CharField(db_comment='创建人', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('deleted_at', models.DateTimeField(db_comment='删除时间', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiInterfaceModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('document_id', models.IntegerField(db_column='所属文档')),
                ('api_title', models.CharField(db_comment='接口标题', max_length=255)),
                ('api_url', models.CharField(db_comment='接口URL路径', max_length=512)),
                ('method', models.CharField(db_comment='请求方法', max_length=20)),
                ('params', models.JSONField(db_comment='请求参数', null=True)),
                ('request_example', models.TextField(db_comment='请求示例', null=True)),
                ('response_example', models.TextField(db_comment='响应示例', null=True)),
                ('comment', models.TextField(db_comment='接口说明', null=True)),
                ('status', models.CharField(db_comment='状态', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('deleted_at', models.DateTimeField(db_comment='删除时间', null=True)),
            ],
        ),
    ]
