# Generated by Django 4.2.27 on 2026-01-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auto_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidocuments',
            name='is_parsed',
            field=models.BooleanField(db_comment='是否已解析', default=False),
        ),
    ]
