# Generated by Django 4.2.27 on 2026-01-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auto_test', '0002_apidocuments_is_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidocuments',
            name='created_user_id',
            field=models.IntegerField(db_comment='创建人id', null=True),
        ),
    ]
