# Generated by Django 4.2.27 on 2026-01-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auto_test', '0004_apitestcasemodel_apitestenvironmentmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiDocuments',
            new_name='ApiDocumentsModel',
        ),
        migrations.AlterModelOptions(
            name='apidocumentsmodel',
            options={'ordering': ['-created_at'], 'verbose_name': '接口文档', 'verbose_name_plural': '接口文档'},
        ),
        migrations.AlterModelOptions(
            name='apiinterfacemodel',
            options={'ordering': ['-created_at'], 'verbose_name': '接口信息', 'verbose_name_plural': '接口信息'},
        ),
        migrations.AlterModelTable(
            name='apidocumentsmodel',
            table='api_documents',
        ),
        migrations.AlterModelTable(
            name='apiinterfacemodel',
            table='api_interfaces',
        ),
    ]
