# Generated by Django 4.2.27 on 2026-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auto_test', '0005_rename_apidocuments_apidocumentsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcasemodel',
            name='module',
            field=models.CharField(blank=True, db_comment='所属模块', max_length=255, null=True),
        ),
    ]
