# Generated by Django 4.2.27 on 2026-01-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDocumentModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(db_column='所属项目')),
                ('doc_name', models.CharField(db_column='需求文档名称', max_length=255)),
                ('version', models.CharField(db_column='版本号', max_length=50, null=True)),
                ('cos_access_url', models.URLField(db_comment='cos访问url', null=True)),
                ('file_size', models.BigIntegerField(db_comment='文件大小（字节）')),
                ('comment', models.TextField(db_comment='备注说明', null=True)),
                ('parse_status', models.SmallIntegerField(choices=[(0, '未解析'), (1, '解析中'), (2, '已解析'), (3, '解析失败')], db_comment='解析状态: 0-未解析, 1-解析中, 2-已解析, 3-解析失败', default=0)),
                ('requirement_count', models.IntegerField(db_comment='解析出的需求项数量', null=True)),
                ('created_user_id', models.IntegerField(db_comment='创建人id')),
                ('created_user', models.CharField(db_comment='创建人', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('deleted_at', models.DateTimeField(db_comment='删除时间', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(db_column='所属项目id')),
                ('requirement_document_id', models.IntegerField(db_column='所属需求文档id')),
                ('requirement_title', models.CharField(db_comment='需求标题', max_length=255, null=True)),
                ('requirement_content', models.TextField(db_column='需求内容')),
                ('module', models.CharField(db_comment='所属模块', max_length=100, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '已审核'), (2, '测试用例生成中'), (3, '测试用例已覆盖'), (4, '已废弃')], db_comment='需求状态: 0-待审核，1-已审核，2-测试用例生成中，3-测试用例已覆盖，4-已废弃', default=0)),
                ('vector_index', models.IntegerField(db_column='FAISS向量索引', null=True)),
                ('is_vectorized', models.BooleanField(db_column='是否已向量化', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('deleted_at', models.DateTimeField(db_comment='删除时间', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementRelationModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('source_requirement_id', models.IntegerField(db_column='源需求id')),
                ('target_requirement_id', models.IntegerField(db_column='目标需求id')),
                ('similarity_score', models.FloatField(db_column='相似度分数（0-1）')),
                ('match_method', models.CharField(db_column='匹配方式：vector/manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('deleted_at', models.DateTimeField(db_comment='删除时间', null=True)),
            ],
        ),
    ]
