# Generated by Django 4.2.27 on 2026-01-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirementdocumentmodel',
            options={'ordering': ['-created_at'], 'verbose_name': '需求文档', 'verbose_name_plural': '需求文档'},
        ),
        migrations.AlterModelOptions(
            name='requirementmodel',
            options={'ordering': ['-created_at'], 'verbose_name': '需求项', 'verbose_name_plural': '需求项'},
        ),
        migrations.AlterModelOptions(
            name='requirementrelationmodel',
            options={'ordering': ['-created_at'], 'verbose_name': '关联需求', 'verbose_name_plural': '关联需求'},
        ),
        migrations.AddField(
            model_name='requirementmodel',
            name='created_user',
            field=models.CharField(db_comment='创建人', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requirementmodel',
            name='created_user_id',
            field=models.IntegerField(db_comment='创建人id', default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='requirementdocumentmodel',
            table='requirement_document',
        ),
        migrations.AlterModelTable(
            name='requirementmodel',
            table='requirement',
        ),
        migrations.AlterModelTable(
            name='requirementrelationmodel',
            table='requirement_relation',
        ),
    ]
