# Generated by Django 4.2.27 on 2026-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_alter_requirementdocumentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementmodel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待审核'), (1, '处理中'), (2, '已审核'), (3, '测试用例生成中'), (4, '测试用例已覆盖'), (5, '已废弃')], db_comment='需求状态: 0-待审核，1-处理中（向量化），2-已审核，3-测试用例生成中，4-测试用例已覆盖，5-已废弃', default=0),
        ),
    ]
